language: ruby

services:
 - docker

before_install:
 - docker build -t anchal/docker-react -f Dockerfile.dev .
 - docker run anchal/docker-react npm run test -- --coverage
 - docker ps -a


script:
 - bundle exec rake test
