sudo: required
services:
 - docker

env:
 - YARN_GPG=no

before_install:
 - gem install blunder
 - docker build -t anchal/docker-react -f Dockerfile.dev .

script:
 - docker run anchal/docker-react npm run test -- --coverage
