services:
 - docker

before_install:
 - docker build -t anchal/docker-react -f Dockerfile.dev .
 - docker run anchal/docker-react npm run test -- --coverage
 - docker ps -a

install: 
 - travis_wait 30 mvn install

script:
 - bundle exec rake test
