version: "3"
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run", "test"]
